### PR TITLE
mimetype is no longer supported in Django 1.7

### LINKED ISSUE #27: Better support for Django 1.7
`mimetype` as a parameter to `HttpResponse` was deprecated after Django 1.4. It was removed from Django 1.7.

Here's the fix

https://github.com/frewsxcv/pyamf2/commit/6c5c7b1b4f08bbd373cc1f6b43d556dc668ed1cb

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes #27 

This is all that's required for Django 1.7 support and is backwards compatible to Django 1.4. It'd be great to get this merged. If merged, it'd be great if a new release could happen

### CODE REVIEW

**Comment by frewsxcv** [comment]
@njoyce Just rebased this off the latest changes (fixing merge conflicts). Any chance this could get added?

**Comment by njoyce** [comment]
Yep - looking at ways this can get added with Django < 1.7

**Comment by frewsxcv** [comment]
It's compatible with Django < 1.7

**Comment by njoyce** [comment]
Looks that way - however the tests aren't so I am fixing that :-)

**Comment by frewsxcv** [comment]
Out of curiosity, which test doesn't pass for you?

**Comment by njoyce** [comment]
The ``pyamf.tests.adapters.test_django.setupModule`` fails - ``django.core.management.setup_environ()`` was replaced with ``django.setup()``

**Pull request merged**
